RIAK_HOST = 'localhost'
RIAK_PORT = 8091
MONGODB_HOST = 'localhost'
MONGODB_PORT = 27017
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
SERVER_PORT = 13000
SERVER_HOST = 'localhost'
DATE_FORMAT = '%d/%m/%Y %H:%M'
STATIC_URL = '/static/'
POLLING_INTERVAL = 60 * 5 #seconds x minutes
DEBUG = True
STOP_WORDS = [',','.',';',':']
VERSION = '2'